build: Add Arm64 builds

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -14,9 +14,8 @@ jobs:
   test-macos:
     runs-on:
       - self-hosted
-      - x64
+      - ARM64
       - macos
-      - sp53
     steps:
       - uses: actions/checkout@v4
 
@@ -321,7 +320,7 @@ jobs:
           echo "patch           : ${{ steps.release.outputs['patch'] }}"
           echo "sha             : ${{ steps.release.outputs['sha'] }}"
 
-  release-macos:
+  release-macos-x64:
     needs: release-please
     runs-on:
       - self-hosted
@@ -432,6 +431,123 @@ jobs:
           draft: true
           tag: ${{ needs.release-please.outputs.release_tag_name }}
           artifacts: ./${{ needs.release-please.outputs.release_tag_name }}-macos.zip
+          token: ${{ github.token }}
+
+      - name: Tidy up before existing
+        run: |
+          pwd
+          ls -la
+
+  release-macos-arm64:
+    needs: release-please
+    runs-on:
+      - self-hosted
+      - ARM64
+      - macos
+    # timeout-minutes: 15
+
+    if: needs.release-please.outputs.releases_created == 'true'
+    env:
+      DIST_FILE_NAME: butler-sheet-icons
+      GITHUB_TOKEN: ${{ secrets.PAT }}
+      MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE_BASE64_CODESIGN }}
+      MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_CODESIGN_PWD }}
+      MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_CODESIGN_NAME }}
+      MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
+      PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
+      PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
+      PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
+    steps:
+      - name: Release tag and upload url from previous job
+        run: |
+          echo "tag_name   : ${{ needs.release-please.outputs.release_tag_name }}"
+          echo "upload_url : ${{ needs.release-please.outputs.release_upload_url }}"
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 23
+
+      - name: Install dependencies
+        run: |
+          pwd 
+          npm ci --include=prod
+
+      - name: Build binaries
+        run: |
+          # Create a single JS file using esbuild
+          ./node_modules/.bin/esbuild src/${DIST_FILE_NAME}.js --bundle --outfile=build.cjs --format=cjs --platform=node --target=node23 --inject:./src/lib/util/import-meta-url.js --define:import.meta.url=import_meta_url
+
+          # Generate blob to be injected into the binary
+          node --experimental-sea-config src/sea-config.json
+
+          # Get a copy of the Node executable
+          cp $(command -v node) ${DIST_FILE_NAME}
+
+          # Remove the signature from the Node executable
+          codesign --remove-signature ${DIST_FILE_NAME}
+
+          # Inject the blob
+          npx postject ${DIST_FILE_NAME} NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 --macho-segment-name NODE_SEA
+
+          # Start signing of the binary    
+          security delete-keychain build.keychain || true
+
+          # -------------------
+          # Turn our base64-encoded certificate back to a regular .p12 file
+          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
+
+          # -------------------
+          # We need to create a new keychain, otherwise using the certificate will prompt
+          # with a UI dialog asking for the certificate password, which we can't
+          # use in a headless CI environment
+          security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
+          security list-keychains -d user -s build.keychain
+          security default-keychain -d user -s build.keychain
+          security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
+          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
+          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
+
+          codesign --force -s "$MACOS_CERTIFICATE_NAME" -v "./${DIST_FILE_NAME}" --deep --strict --options=runtime --timestamp --entitlements ./release-config/${DIST_FILE_NAME}.entitlements
+
+          # -------------------
+          # We can't notarize an app bundle directly, but we need to compress it as an archive.
+          # Therefore, we create a zip file containing our app bundle, so that we can send it to the
+          # notarization service
+          # Notarize release binary
+          echo "Creating temp notarization archive for release binary"
+          ditto -c -k --keepParent "./${DIST_FILE_NAME}" "./${{ needs.release-please.outputs.release_tag_name }}-arm64-macos.zip"
+
+          # -------------------
+          # Here we send the notarization request to the Apple's Notarization service, waiting for the result.
+          # This typically takes a few seconds inside a CI environment, but it might take more depending on the App
+          # characteristics. Visit the Notarization docs for more information and strategies on how to optimize it if
+          # you're curious
+          echo "Notarize release app"
+          xcrun notarytool submit "./${{ needs.release-please.outputs.release_tag_name }}-arm64-macos.zip" --keychain-profile "notarytool-profile" --wait
+
+          # -------------------
+          # Clean up
+          # Delete build keychain
+          security delete-keychain build.keychain
+          rm build.cjs
+
+          ls -la
+
+      - name: Upload to existing release
+        uses: ncipollo/release-action@v1
+        with:
+          allowUpdates: true
+          omitBodyDuringUpdate: true
+          omitNameDuringUpdate: true
+          artifactContentType: raw
+          # artifactContentType: application/zip
+          draft: true
+          tag: ${{ needs.release-please.outputs.release_tag_name }}
+          artifacts: ./${{ needs.release-please.outputs.release_tag_name }}-arm64-macos.zip
           token: ${{ github.token }}
 
       - name: Tidy up before existing
